name: Deploy Backend to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ${{ secrets.BACKEND_PATH }}
                      git pull origin main
                      composer install --no-interaction --prefer-dist --optimize-autoloader
                      php artisan migrate --force
                      php artisan config:cache
                      php artisan route:cache
                      sudo systemctl restart httpd
